// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface AppState {
  route: string,
  theme: string,
  workspace: string,
  current_project_path: string
}

interface State {
  appState?: AppState,
  workspace?: Workspace,
  project?: Project,
  characters?: Character[],
  parts?: Part[]
}

interface Workspace { 
  current_project_title: string, 
  projects: Array<Project>, 
}

interface Project { 
  title: string; 
  path: any; 
  isCurrentlyOpen: boolean;
  cover: string,
  route: { current: string }
}

interface Chapters {
  chapters: Chapter[]
}

interface Chapter {
  id: string,
  title: string,
  part: number,
  position: number,
  deleted_at?: Date
}

interface Characters {
  characters: Character[]
}

interface Character {
  id: number,
  first_name: string,
	last_name: string,
	nickname?: string,
  deleted_at?: date
}

interface Part {
  position: number,
  name: string
}

interface Scenes {
  scenes: []
}

interface Scene {
	from: Date,
	to: Date,
	location_id: number,
	title: string,
	subtitle: string,
	summary: string,
	text: string,
	chapter: number,
	position: number,
	deleted_at: Date
};