// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

interface State {
  appState?: AppState,
  workspace?: Workspace,
  project?: Project
}

interface AppState {
  theme: string,
  current_project_title: string,
  current_project_path: string
}

interface Workspace { 
  path: string, 
  projects: Array<Project>, 
}

interface Project { 
  title: string; 
  path: string; 
  isCurrentlyOpen: boolean;
  cover: string,
  route: { current: string }
}

interface Chapters {
  chapters: []
}

interface Chapter {
  id: string,
  title: string,
  position: number,
  deleted_at: Date
}